name: run autoupdate

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            persist-credentials: false  # Avoid using the default GitHub token
            
      - uses: actions/setup-python@master
        with:
          python-version: '3.x'

      - run: python3 -m pip install -r requirements.txt

      - run: python3 autoupdate.py
        env:
          BUTTONWEAVERS_PW: ${{ secrets.BUTTONWEAVERS_PW }}

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'automated execution of autoupdate.py'
          git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main

